export default [
  {
    id: "diary_001",
    content:
      "今天天气很好，去公园散步了，心情愉快。看到了很多花开了，春天真美好。",
    date: "2026-01-10",
    mood: "happy",
    tags: ["生活", "散步"],
  },
  {
    id: "diary_002",
    content: "读了一本关于人工智能的书，很有启发。",
    date: "2026-01-11",
    mood: "excited",
    tags: ["学习", "科技"],
  },
  {
    id: "diary_003",
    content: "和朋友一起吃了顿美味的晚餐，聊了很多。",
    date: "2026-01-12",
    mood: "happy",
    tags: ["生活", "聚餐"],
  },
  {
    id: "diary_004",
    content:
      "今天天气很好，去公园散步了，心情愉快。看到了很多花开了，春天真美好。",
    date: "2026-01-10",
    mood: "happy",
    tags: ["生活", "散步"],
  },
  {
    id: "diary_005",
    content: "读了一本关于人工智能的书，很有启发。",
    date: "2026-01-11",
    mood: "excited",
    tags: ["学习", "科技"],
  },
  {
    id: "diary_006",
    content: "和朋友一起吃了顿美味的晚餐，聊了很多。",
    date: "2026-01-12",
    mood: "happy",
    tags: ["生活", "聚餐"],
  },
  {
    id: "diary_007",
    content:
      "今天天气很好，去公园散步了，心情愉快。看到了很多花开了，春天真美好。",
    date: "2026-01-10",
    mood: "happy",
    tags: ["生活", "散步"],
  },
  {
    id: "diary_008",
    content: "读了一本关于人工智能的书，很有启发。",
    date: "2026-01-11",
    mood: "excited",
    tags: ["学习", "科技"],
  },
  {
    id: "diary_009",
    content: "和朋友一起吃了顿美味的晚餐，聊了很多。",
    date: "2026-01-12",
    mood: "happy",
    tags: ["生活", "聚餐"],
  },
  {
    id: "diary_010",
    content:
      "今天天气很好，去公园散步了，心情愉快。看到了很多花开了，春天真美好。",
    date: "2026-01-10",
    mood: "happy",
    tags: ["生活", "散步"],
  },
  {
    id: "diary_011",
    content: "读了一本关于人工智能的书，很有启发。",
    date: "2026-01-11",
    mood: "excited",
    tags: ["学习", "科技"],
  },
  {
    id: "diary_012",
    content: "和朋友一起吃了顿美味的晚餐，聊了很多。",
    date: "2026-01-12",
    mood: "happy",
    tags: ["生活", "聚餐"],
  },
  {
    id: "diary_013",
    content:
      "今天天气很好，去公园散步了，心情愉快。看到了很多花开了，春天真美好。",
    date: "2026-01-10",
    mood: "happy",
    tags: ["生活", "散步"],
  },
  {
    id: "diary_014",
    content: "读了一本关于人工智能的书，很有启发。",
    date: "2026-01-11",
    mood: "excited",
    tags: ["学习", "科技"],
  },
  {
    id: "diary_015",
    content: "和朋友一起吃了顿美味的晚餐，聊了很多。",
    date: "2026-01-12",
    mood: "happy",
    tags: ["生活", "聚餐"],
  },
  {
    id: "diary_016",
    content:
      "今天天气很好，去公园散步了，心情愉快。看到了很多花开了，春天真美好。",
    date: "2026-01-10",
    mood: "happy",
    tags: ["生活", "散步"],
  },
  {
    id: "diary_017",
    content: "读了一本关于人工智能的书，很有启发。",
    date: "2026-01-11",
    mood: "excited",
    tags: ["学习", "科技"],
  },
  {
    id: "diary_018",
    content: "和朋友一起吃了顿美味的晚餐，聊了很多。",
    date: "2026-01-12",
    mood: "happy",
    tags: ["生活", "聚餐"],
  },
  {
    id: "diary_019",
    content:
      "今天天气很好，去公园散步了，心情愉快。看到了很多花开了，春天真美好。",
    date: "2026-01-10",
    mood: "happy",
    tags: ["生活", "散步"],
  },
  {
    id: "diary_020",
    content: "读了一本关于人工智能的书，很有启发。",
    date: "2026-01-11",
    mood: "excited",
    tags: ["学习", "科技"],
  },
  {
    id: "diary_021",
    content: "和朋友一起吃了顿美味的晚餐，聊了很多。",
    date: "2026-01-12",
    mood: "happy",
    tags: ["生活", "聚餐"],
  },
  {
    id: "diary_022",
    content:
      "今天天气很好，去公园散步了，心情愉快。看到了很多花开了，春天真美好。",
    date: "2026-01-10",
    mood: "happy",
    tags: ["生活", "散步"],
  },
  {
    id: "diary_023",
    content: "读了一本关于人工智能的书，很有启发。",
    date: "2026-01-11",
    mood: "excited",
    tags: ["学习", "科技"],
  },
  {
    id: "diary_024",
    content: "和朋友一起吃了顿美味的晚餐，聊了很多。",
    date: "2026-01-12",
    mood: "happy",
    tags: ["生活", "聚餐"],
  },
];
