
const COLLECTION_NAME_EBOOK = "ebook";
const VECTOR_DIM = 1024;
const BOOK_ID = 1;
const SIMILARITY_THRESHOLD = 0.35;
const MAX_TOKENS = 200;
const MAX_HISTORY_MESSAGES = 40;
export { COLLECTION_NAME_EBOOK, VECTOR_DIM, BOOK_ID, SIMILARITY_THRESHOLD, MAX_TOKENS, MAX_HISTORY_MESSAGES };